// ** Nextjs Imports
import { Gemunu_Libre } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

// ** CSS Imports
import "./globals.css";

// ** Custom Components
import Header from "@/components/navbar";
import Footer from "@/components/Footer";

const inter = Gemunu_Libre({ subsets: ["latin"] });

export const metadata = {
  title: "Yunus's Portfolio",
  description: "Generated by create next app",
  url: "https://yunsturann.vercel.app/",
  type: "website",
  siteName: "Yunus's Portfolio",
  keywords: ["web development", "programming", "portfolio"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
