import { Gemunu_Libre } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import Footer from "@/components/Footer";

const inter = Gemunu_Libre({ subsets: ["latin"] });

export const metadata = {
  title: "Yunus's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Yunus Turan" />
        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
