import { Gemunu_Libre } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import Footer from "@/components/Footer";

const inter = Gemunu_Libre({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
