import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const merri = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${merri.className} bg-page`}>
        <main className="max-lg:px-[4%] max-w-5xl mx-auto text-default-text max-h-screen  ">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
